version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: install-all-reqs.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: run-project.sh
      timeout: 300
      runas: root
